language: cpp
dist: bionic
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - cmake
    - libsdl2-dev
    - mesa-utils
    - linux-generic
    - xserver-xorg-core
    - xserver-xorg
    - xserver-xorg-video-all
    - xserver-xorg-input-all
    - libwayland-egl1-mesa
    - pulseaudio
before_install:
  - pip install --user codecov
before_script:
  # evironment for live tests
  - dbus-launch pulseaudio --start
  - export SDL_AUDIODRIVER=pulseaudio

  - /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX
  - export SDL_VIDEODRIVER=x11
  - export DISPLAY=:99.0
script:
  - make test
after_success:
  - codecov
