jobs:
  allow_failures:
    os: windows
language: cpp
os:
  - linux
  - osx
  - windows
compiler:
  - clang
  - gcc
addons:
  apt:
    update: true
    packages:
    - cmake
    - libsdl2-dev
    - mesa-utils
    - linux-generic
    - xserver-xorg-core
    - xserver-xorg
    - xserver-xorg-video-all
    - xserver-xorg-input-all
    - libwayland-egl1-mesa
    - pulseaudio
  homebrew:
    update: true
    packages:
    - cmake
    - sdl2
  chocolatey:
    update: true
    packages:
    - python
    - cmake
before_script:
  - pip install --user codecov
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      dbus-launch pulseaudio --start;
      export SDL_AUDIODRIVER=pulseaudio;

      /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
      export SDL_VIDEODRIVER=x11;
      export DISPLAY=:99.0;
    fi
script:
  - make test
after_success:
  - codecov
