addons:
  apt:
    update: true
    packages:
      - cmake
      - libsdl2-dev
      - mesa-utils
      - linux-generic
      - xserver-xorg-core
      - xserver-xorg
      - xserver-xorg-video-all
      - xserver-xorg-input-all
      - libwayland-egl1-mesa
      - pulseaudio
      - doxygen
  homebrew:
    update: true
    packages:
      - cmake
      - sdl2

jobs:
  stages:
    - Test using GCC in Windows
    - Test using Clang in Linux
    - Test using GCC in Linux
    - Test using Clang in OSX
    - Documentation Generation
  include:
    - stage: Test using MSVC in Windows
      os: windows
      language: cpp
      compiler: gcc
      before_script:
        - choco install python --version 3.8.1
        - choco install cmake
        - choco install make
        - python Script/WindowsCI.py
      script:
        - make test-windows
      env: PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/CMake/bin:/c/ProgramData/chocolatey/bin:$PATH"
    - stage: Test using Clang in Linux
      os: linux
      language: cpp
      compiler: clang
      before_script:
        - dbus-launch pulseaudio --start;
          export SDL_AUDIODRIVER=pulseaudio;

          /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
          export SDL_VIDEODRIVER=x11;
          export DISPLAY=:99.0;
      script:
        - make test
    - stage: Test using GCC in Linux
      os: linux
      language: cpp
      compiler: gcc
      before_script:
        - dbus-launch pulseaudio --start;
          export SDL_AUDIODRIVER=pulseaudio;

          /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
          export SDL_VIDEODRIVER=x11;
          export DISPLAY=:99.0;
      script:
        - make test
    - stage: Test using Clang in OSX
      os: osx
      language: cpp
      compiler: clang
      script:
        - make test
    - stage: Documentation Generation
      if: os = linux
      language: generic
      before_deploy:
        - doxygen
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: ./Docs/html
        github_token: $GITHUB_TOKEN
        on:
          branch: master
