jobs:
  - job: Test
    displayName: Testing on multiple OS
    condition: true
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-18.04
        MacOS:
          vmImage: macOS-10.14
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)
    steps:
      - script: |
          set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\
          mkdir build
          cd build
          cmake ..
          msbuild HexagonEngine.sln
#          ./Test/HexagonEngineTest
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: Test using Windows
      - script: |
          brew install sdl2
          mkdir build
          cd build
          cmake ..
          make
          ./Test/HexagonEngineTest
        condition: eq( variables['Agent.OS'], 'Darwin' )
        displayName: Test using MacOS
      - script: |
          sudo apt update
          sudo apt install libsdl2-dev mesa-utils linux-generic xserver-xorg-core xserver-xorg xserver-xorg-video-all xserver-xorg-input-all libwayland-egl1-mesa pulseaudio
      
          dbus-launch pulseaudio --start
          export SDL_AUDIODRIVER=pulseaudio

          /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GL
          export SDL_VIDEODRIVER=x11;
          export DISPLAY=:99.0;

          mkdir build
          cd build
          cmake ..
          make
          ./Test/HexagonEngineTest
        condition: eq( variables['Agent.OS'], 'Linux' )
        displayName: Test using Linux
